/*
 * HmOpenAiGpt v 1.0.0.1
 *
 * Copyright (c) 2024 Akitsugu Komiyama
 * under the MIT License
 */


hidemaruversion "9.25.99";

jsmode @"WebView2\HmOpenAiGpt";
js {


// ------------- 会話エンジンの設定項目 -------------

let openai_key = getenv("OPENAI_API_KEY") || getenv("OPENAI_KEY");
if (!openai_key) {
    openai_key = ""; // 直接ここでAPIのKEYの文字列を指定しても良いですが、あまり推奨はしません。直書きする場合、このマクロを迂闊に配布して他者にAPIのキーが漏れないよう注意。
}
if (!openai_key) {
    message("OPENAIのキーが空です");
    throw "OPENAIのキーが空です";
}

const model = "gpt-3.5-turbo"; // "gpt-4o"などの設定可能。しかしながら値段が10倍に跳ね上がるので注意。
                               // "gpt-4-turbo" は、「値段が高いだけで低性能で利用価値なし」なので注意

const max_tokens = 4000;       // この数値は概ね 使用対象のmodelの最大トークンの半分程度を使用するのが望ましい。
                               // 「gpt-3.5-turbo なら 2000」「gpt-4o なら 4000」が目安

const renderpane_custom_param = {
    place: "rightside",        // leftside | rightside | upside | downside
    size: 400,                 // 左や右の配置の時は、横幅のこと。上や下の配置の時は縦幅のこと。
};

// --------------------------------------------------

var currentmacrodir = currentmacrodirectory();

// declare var avilablePort;

// 有効ポートの受け口。非同期にてここにopenHttpServer関数で代入される(可能性がある)
if (typeof(avilablePort) == "undefined") {
    openHttpServer();
}

// 簡易Httpサーバーを立てる。ポート自体付きでサーバーを立てることが出来ない限定的なマシンだと失敗するだろう。
function openHttpServer() {
    function getExtractPort(text) {
        const match = text.match(/PORT:(\d+)/);
        return match ? match[1] : null;
    }

    try {
        // このウィンドウハンドルの値を私ながら簡易サーバーを立ち上げる。
        let currentWindowHandle = hidemaru.getCurrentWindowHandle();

        // このウィンドウハンドルがなくなったら、2秒後に「該当の簡易サーバー」は自動終了する
        // 簡易サーバーがどんどん増えるといったことはなくなる。
        let processInfo = hidemaru.runProcess('"' + currentmacrodir + "\\HmSimpleHttpServer.exe" + '"' + " " + currentWindowHandle, currentmacrodir, "stdioAlive", "sjis");

        // 簡易サーバープログラムの出力を非同期で読み取る。
        // 簡易サーバープログラムはサーバーを起動するとともに、確保したポート番号を標準出力に出す。
        let stdOut = processInfo.stdOut;
        stdOut.onReadLine(readLineAsync);

        // この関数は非同期で呼ばれる
        function readLineAsync(serverOutputText) {
            let port = getExtractPort(serverOutputText);
            if (port == 0) {
                throw "HTTPサーバーのためのポートが確保できませんでした";
            }
            if (port != null) {
                avilablePort = port;
                hidemaru.postExecMacroMemory("js { doMain() }");
            }
        }

    } catch (err) {
        outputAlert(err);
    }
}



// レンダリングペインを指定属性＆ポートでオープン
function openRenderPaneCommand(port) {

    let baseUrl = new URL("http://localhost:" + port + "/HmOpenAiGpt.html");

    // このJS内にあるコールバック用にも使う関数をレンダリング枠にクエリーparamとして伝達
    let idHtmlButtonClick = hidemaru.getFunctionId(onHtmlButtonClick);
    let params = new URLSearchParams();
    params.set('idHtmlButtonClick', String(idHtmlButtonClick));

    baseUrl.search = params.toString();
    let targetUrl = baseUrl.href; // オブジェクトから実際のUrl文字列へ

    const renderpane_json_param = {
        target: "HmOpenAiGpt",
        uri: targetUrl,
        show: 1,
        place: "rightside",
        size: 400,
        initialize: "async",
    };

    // ユーザー指定のもので上書き。
    const renderpane_mix_param = { ...renderpane_json_param, ...renderpane_custom_param };

    renderpanecommand(renderpane_mix_param)
}



var currentexepath = currentmacrodir + "\\HmOpenAiGpt.exe";

// エラー用途
function outputAlert(msg) {
    let hidemaruexedir = hidemarudir();
    let dll = loaddll(hidemaruexedir + "\\HmOutputPane.dll");
    dll.dllFuncW.Output(msg + "\r\n");
}

// ユーザーの「質問内容」が入るテキストファイル
var questionFileName = currentmacrodir + "\\HmOpenAiGpt.question.txt";
var answerFileName = currentmacrodir + "\\HmGoogleGemini.txt";

// 質問内容の1行目に「時刻」を入れることで、質問時刻がわかるようにしている。
// これはシステムが「ファイルの更新」を非常に頻繁に誤爆して多重検知するために必要。
// 多重検知した際に、「その内容はもう受付済み」という判断をするために「時刻」を質問内容に刻むようにしている。
function getTickCount() {
    return tickcount() & 0x7fffffff;
}

// 選択テキストを質問内容としてファイルに保存し、ＡＩを指定のパラメータやモデルで起動
function doSendQuestionContent() {
    let text = hidemaru.getSelectedText();
    let commandline = `"${currentexepath}" "${openai_key}" "${model}" "${max_tokens}"`;
    runex(commandline, 0, 0, "", 0, "", 0, "", 0, "", 2, 1, 0, 0);
//      runex(commandline, 0); // デバッグ用

    let sendcmd = "HmOpenAiGpt.Message(" + getTickCount() + ")\n";
    hidemaru.setTimeout(
        () => { hidemaru.saveTextFile(questionFileName, sendcmd + text, "utf8"); },
        200
    );
}

function onHtmlButtonClick(text) {
    if (text == "reset") {
        hidemaru.postExecMacroMemory( "js { resetAI(); }");
    }
    else if (text == "stop") {
        hidemaru.postExecMacroMemory( "js { stopAIAnswer(); }");
    }
}

function stopAIAnswer() {
    let sendcmd = "HmOpenAiGpt.Cancel(" + getTickCount() + ")\n";
    let text = "応答を停止";
    let commandline = `"${currentexepath}" "HmOpenAiGpt.Cancel()"`;
    runex(commandline, 0, 0, "", 0, "", 0, "", 0, "", 2, 1, 0, 0);
    hidemaru.saveTextFile(questionFileName, sendcmd + text, "utf8");
}

function resetAI() {
    let sendcmd = "HmOpenAiGpt.Clear(" + getTickCount() + ")\n";
    let text = "リセット";
    let commandline = `"${currentexepath}" "HmOpenAiGpt.Clear()"`;
    runex(commandline, 0, 0, "", 0, "", 0, "", 0, "", 2, 1, 0, 0);
    hidemaru.saveTextFile(questionFileName, sendcmd + text, "utf8");
    hidemaru.saveTextFile(answerFileName, "", "utf8");
}

function pasteAIAnswer() {
    let text = hidemaru.loadTextFile(answerFileName);
    insert(text);
}

// テキストを選択せずに、このマクロを実行した時は、
// 「ＡＩの応答を途中キャンセル」あるいは「ＡＩを完全にリセットしてプロセス自体を終了し、会話履歴も消去」することが出来る。
function doSendCommand() {
    let selectMenuID = menu("応答を停止 (&S)", "全リセット (&R)", "応答を張り付け (&V)");
    if (selectMenuID == 1) {
        stopAIAnswer();
    }
    else if (selectMenuID == 2) {
        resetAI();
    }
    else if (selectMenuID == 3) {
        pasteAIAnswer();
    }
}


// HTML/JS用のHttpサーバーを起動。(PHPだと他の環境要らずでたった２個ほどのファイルでシンプルサーバーが動作するので一緒に内包してある)

// 選択範囲の最終座標に移動した方が便利だとわかっている
function gotoSelectEndPosition() {
    // 選択は自動解除した方が便利なようだ
    let cur_selendx = selendx();
    let cur_selendy = selendy();
    escapeselect();
    moveto(cur_selendx, cur_selendy);
}

// メイン処理
function doMain() {
    try {
        // レインだリングペインをそのポートでlocalhostで開く
        openRenderPaneCommand(avilablePort);

        // 文字列を選択しているなら
        if (selecting()) {
            // それをＡＩへの質問内容として送信
            doSendQuestionContent();
            // 選択を解除し、選択の最後の座標へと移動
            gotoSelectEndPosition();
        } else {
            // それ以外なら、ＡＩにコマンドの送信
            doSendCommand();
        }
    } catch (err) {
        outputAlert(err);
    }
}

doMain();

} // js

